apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab1
  template:
    metadata:
      labels:
        app: lab1
    spec:
      containers:
      - name: demo-container
        image: nginx:1.19
        ports:
        - containerPort: 80
