apiVersion: v1
kind: Service
metadata:
  name: lab2-clusterip-service
spec:
  selector:
    app: lab2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab2-nodeport-service
spec:
  selector:
    app: lab2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
